name: update-subs

on:
  schedule:
    # هر ۱ ساعت از ساب اصلی آپدیت بگیر
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: pip install pyyaml
      - run: python split.py
      - name: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add subs/ README.md
          git diff --cached --quiet || git commit -m "auto: update per-country subs $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push
